### ISSUE TITLE
Cannot install conda environment from existing environment.yml file

### ISSUE THREAD

**Issue by heruiyang** [raphael-group/GASTON#1]
Hi,

Thanks very much for creating this very interesting and useful method! I've been testing it out on some spatial datasets and just wanted to make a note that I had initially run into some issues with installing the conda environment to run the package from the ```environment.yml``` file. 

I ended up fixing the issue by removing the build strings (the strings after the second ```=``` in the package list) for all packages, as well as some (presumably OS-specific) packages that were causing problems, namely ```libcups```, ```libgcc-ng```, ```libnsl```, ```libgfortran-ng```, ```libstdcxx-ng```, ```keyutils```, ```libxkbcommon```, and ```_openmp_mutex```. After that I could install the environment and run the GASTON package.

I'm creating the issue for reference just in case anyone else runs into this problem, and so that the authors can update the yml file (e.g. using ```conda env export --no-builds``` should create a yml file with no build strings). Thanks again for your hard work in putting this method together!

**Comment by uthsavc** [comment]
Hi! Sorry for the late reply -- I just saw this message -- and thank you for the interest in GASTON! I did not realize the build strings are an issue. I just pushed an update which removes the build strings from the `environment.yml` file as suggested. 

Thanks for figuring this out! Please let me know if installation works now, and also if you have any other questions! 
(Also feel free to email me directly at uchitra@princeton.edu, I am more likely to see an email)

**Comment by parth2608** [comment]
Hi, 

After the update, it fails to correctly install and the setup fails.

**Comment by uthsavc** [comment]
@parth2608 Oops, I always forget to remove the gaston package line. I just pushed an update. Can you try installing now?

**Comment by kimsjune** [comment]
Hi,

Awesome tool! Leaving this here for anyone working on a Mac.

### Platform

Apple M4 Max Sequoia 15.5

### The error

```shell
% conda env create -f environment.yml -n gaston
Channels:
 - conda-forge
 - bioconda
 - defaults
 - pyg
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - mkl=2022.2.1*
  - libxkbcommon=1.0.1*
  - libstdcxx-ng=13.2.0*
  - libnsl=2.0.0*
  - libgfortran-ng=13.2.0*
  - libgcc-ng=13.2.0*
  - libcups=2.3.3*
  - ld_impl_linux-64=2.40*
  - keyutils=1.6.1*
  - icu=58.2*
  - _openmp_mutex=4.5*
  - _libgcc_mutex=0.1*

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://conda.anaconda.org/pyg

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

## Solution

There seems to be some Linux (I think) specific packages, so just comment those out in `environment.yml`.

```yml
name: gaston-package
channels:
  - conda-forge
  - bioconda
  - defaults
  - pyg
dependencies:
#  - _libgcc_mutex=0.1
#  - _openmp_mutex=4.5
  - anndata=0.9.2
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.2.3
  - asttokens=2.4.0
  - async-lru=2.0.4
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - colorama=0.4.6
  - comm=0.1.4
  - contourpy=1.1.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dbus=1.13.18
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - filelock=3.12.4
  - fontconfig=2.14.2
  - fonttools=4.42.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h5py=3.9.0
  - hdf5=1.14.0
#  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - isoduration=20.11.0
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - jpeg=9e
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.1
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.6
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.25.0
#  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lcms2=2.15
#  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20230802.1
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang=14.0.6
  - libclang13=14.0.6
#  - libcups=2.3.3
  - libcurl=7.88.1
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
#  - libgcc=13.2.0
 # - libgfortran=13.2.0
 # - libgfortran5=13.2.0
  - libgfortran
  - libglib=2.78.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libnghttp2=1.52.0
#  - libnsl=2.0.0
  - libopenblas=0.3.24
  - libpng=1.6.39
  - libpq=12.15
  - libprotobuf=4.23.4
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
#  - libstdcxx-ng=13.2.0
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libuv=1.46.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.16
#  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - llvmlite=0.40.1
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
#  - mkl=2022.2.1
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=5.7.24
  - natsort=8.4.0
  - nbclient=0.8.0
  - nbconvert-core=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.92
  - numba=0.57.1
  - openssl=3.1.3
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.16.1
  - pynndescent=0.5.10
  - pyparsing=3.1.1
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytorch=2.0.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - referencing=0.30.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.3
  - scanpy=1.9.5
  - scikit-learn=1.3.1
  - scipy=1.11.2
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - session-info=1.0.0
  - setuptools=68.2.2
  - sip=6.6.2
  - six=1.16.0
  - sleef=3.5.1
  - sniffio=1.3.0
  - soupsieve=2.5
  - sqlite=3.43.0
  - stack_data=0.6.2
  - statsmodels=0.14.0
  - stdlib-list=0.8.0
  - sympy=1.12
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tinycss2=1.2.1
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - umap-learn=0.5.4
  - uri-template=1.3.0
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.3
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiobotocore==2.5.4
      - aiohttp==3.8.6
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - asciitree==0.3.3
      - async-timeout==4.0.3
      - botocore==1.31.17
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==2.2.1
      - colorcet==3.0.1
      - dask==2023.10.0
      - dask-image==2023.8.1
      - datashader==0.15.2
      - datashape==0.5.2
      - distributed==2023.10.0
      - docrep==0.3.2
      - fasteners==0.19
      - fiona==1.9.5
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - geopandas==0.14.0
      - glmpca==0.1.0
      - gseapy==1.1.3
      - igraph==0.10.8
      - imageio==2.31.5
      - inflect==7.0.0
      - jmespath==1.0.1
      - kneed==0.8.5
      - lazy-loader==0.3
      - leidenalg==0.10.1
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - matplotlib-scalebar==0.8.1
      - mdurl==0.1.2
      - msgpack==1.0.7
      - multidict==6.0.4
      - multipledispatch==1.0.0
      - multiscale-spatial-image==0.11.2
      - numcodecs==0.12.0
      - numpy==1.23.4
      - ome-zarr==0.8.2
      - omnipath==1.0.7
      - param==1.13.0
      - partd==1.4.1
      - pims==0.6.1
      - pyarrow==13.0.0
      - pyct==0.5.0
      - pydantic==2.4.2
      - pydantic-core==2.10.1
      - pygeos==0.14
      - pyproj==3.6.1
      - pywavelets==1.4.1
      - rich==13.6.0
      - s3fs==2023.6.0
      - scikit-image==0.20.0
      - shapely==2.0.2
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==0.3.0
      - spatialdata==0.0.14
      - squidpy==1.3.1
      #- tbb==2021.10.0
      - tblib==2.0.0
      - texttable==1.7.0
      - tifffile==2023.9.26
      - toolz==0.12.0
      - urllib3==1.26.17
      - validators==0.22.0
      - wrapt==1.15.0
      - xarray==2022.12.0
      - xarray-dataclasses==1.6.0
      - xarray-datatree==0.0.12
      - xarray-schema==0.0.3
      - xarray-spatial==0.3.7
      - yarl==1.9.2
      - zarr==2.16.1
      - zict==3.0.0
prefix: /n/fs/ragr-data/users/uchitra/miniconda3/envs/gaston-package

```

Then install from github with pip: `pip install git+https://github.com/cafferychen777/GASTON.git`.

(That PR hasn't been merged yet, but seems to be valid)

With `device = 'mps'`, the training completed in ~18 min for the colorectal cancer data.
